# Generated by Django 6.0.4 on 2026-04-09 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0002_tags_tasks_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='tag',
            new_name='tags',
        ),
    ]
